### ISSUE TITLE
Custom apiUrl Example

### ISSUE THREAD

**Issue by hroma** [kommitters/editorjs-inline-image#119]
### Is your feature request related to a problem? Please describe.

Unsplash is great but what if my pictures/images/video are stored on my server/cloud? I see that config.apiUrl can be whatever I want. But how the apiUrl response should look like? Are paths of inserted media relative or absolute? What if I drag and drop a media inside editorjs from the same page (list of available images for example)?

### Describe the solution you'd like

Maybe adding a dedicated "Custom apiUrl" section in the README.md including the following:

**Expected response example:**

```
{
  "id": "myuniqueid",
  "width": imgwidth,
  "height": imgheight,
  "urls": {
    "full": "articles/1/img/myimage.jpg",
    "thumb": "articles/1/img/myimage_thumb.jpg"
  },
},
{
  "id": "myuniqueid2",
  "width": imgwidth,
  "height": imgheight,
  "urls": {
    "full": "articles/1/img/myimage2.jpg",
    "thumb": "articles/1/img/myimage2_thumb.jpg"
  },
}
```

**other custom apiUrl config options like:**
`config.imageAddedPath= "absolute/relative", `
// option for path option? isn't better for local ressources to have relative paths so it's easier to maintain? host can be adapted on backend (dev server, prod server, amazon bucket, etc...)`

**drag and drop from list on the same page:**
`config.imageDropped= "data or path", `
//  it would be great to have an option to have the relative path inserted like <img src="/img/example.jpg" instead of having image inserted as <img src="data:image/jpg;base64,...

**Comment by MarioRodriguezS** [comment]
@hroma Thanks a lot for reporting the issue. Here are some points to discuss.

### Custom Api Response

You can customize an API URL different from Unsplash by ensuring it includes the route `/search/photos` and responds with images. Additionally, the request parameters {query: string, per_page: number, orientation: string} are sent in the request from editorjs-inline-image: the orientation param was added in the latest version of `editorjs-inline-image`, the query is the text typed in the plugin input and per_page is the expected images per page in the request, default is 30.

The expected API result is:

```JSON
{
    "results": [
    {
    "urls": {
        "full": "https://your_custom_api/image",
        "thumb": "https://your_custom_api/image_thumb"
    },
    "links": {
        "download_location": "https://your_custom_api/endpoint_to_track_image_uses"
    },
    "user": {
        "name": "author_name",
        "links": {
            "html": "author_profile_link"
        }
    }
    }
    ]
}
```
In the results array, should be added the respective images.

### Option for path option

I have some questions in order to understand your suggestion. If the idea is to set a new attribute for config in the EditorJS instance like  `config.imageAddedPath= "absolute/relative"`, how the user is going to select the local image?, is the user going to type the local image route in the search input in the plugin? or there will be a new option tab in the plugin panel to type the local path?.

![Screenshot 2024-04-04 at 3 45 15 PM](https://github.com/kommitters/editorjs-inline-image/assets/64106728/ec136dfd-ab2f-420d-9ff1-20a3dcd980c4)

Could you please give us a most detailed version of your suggestion?

### Drag and drop from list on the same page

Where would the image be located for dragging? The image would be inside EditorJS?, if that is the case we have a plugin called [editorjs-drag-drop](https://github.com/kommitters/editorjs-drag-drop) to drag and drop blocks inside EditorJS. Could you please give us a most detailed version of your suggestion?

Thanks again for your report. Looking forward to your reply.

Cheers!
